### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by yermulnik** [InfoSec812/sonar-oauth2#4]
```
#> mvn clean verify
[...]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project sonar-oauth2: Compilation failure
[ERROR] /[...]/InfoSec812/sonar-oauth2/src/main/java/org/sonar/plugins/oauth2/OAuth2AuthenticationFilter.java:[65,8] error: cannot find symbol
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project sonar-oauth2: Compilation failure
/[...]/InfoSec812/sonar-oauth2/src/main/java/org/sonar/plugins/oauth2/OAuth2AuthenticationFilter.java:[65,8] error: cannot find symbol

        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.CompilationFailureException: Compilation failure
/[...]/InfoSec812/sonar-oauth2/src/main/java/org/sonar/plugins/oauth2/OAuth2AuthenticationFilter.java:[65,8] error: cannot find symbol

        at org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:656)
        at org.apache.maven.plugin.CompilerMojo.execute(CompilerMojo.java:128)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        ... 19 more
```

**Comment by yermulnik** [comment]
Fixed with attached diff (builds w/o running tests — `-DskipTests`)
[OAuth2AuthenticationFilter.java.txt](https://github.com/InfoSec812/sonar-oauth2/files/455254/OAuth2AuthenticationFilter.java.txt)

**Comment by InfoSec812** [comment]
The code uses Lombok annotation processor to automatically create the suggested logger, so your change is not really needed. Make sure you are using a recent version of Maven and Java, and the annotation processor will work.

**Comment by yermulnik** [comment]
Plugin doesn't work anyway =(

```
2016.09.05 08:09:50 ERROR web[o.a.c.c.C.[.[.[/sonarqube/sonar01]] Exception sending context initialized event to listener instance of class org.sonar.server.platform.PlatformServletContextListener
org.sonar.api.utils.MessageException: File is not a plugin. Please delete it and restart: /opt/sonar/extensions/plugins/sonar-oauth2-1.0-SNAPSHOT.jar
```

**Comment by yermulnik** [comment]
Maven and Java doesn't seem to be outdated:

```
#> mvn --version
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.8.0_101, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: ru_UA, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-37-generic", arch: "amd64", family: "unix"
```

**Comment by InfoSec812** [comment]
Maven 3.3.x would be preferred.

**Comment by yermulnik** [comment]
I'm using latest one from repo for my distro (Mint).
And I'd really appreciate if you can update the plugin to work with recent SonarQube (5.5 or 5.6).
Thanx in advance.

**Comment by InfoSec812** [comment]
George,

```
I appreciate your report of this issue, but Maven 3.0.5 doesn't even
```

support SNI (SSL virtual hosts), so I am unwilling to try to debug until
such time as you try maven 3.3.x as a minimum. I will be doing some
investigation a little later today, though I have had no issues running
against SonarQube 6.x.

Thanks,
Deven

**Comment by InfoSec812** [comment]
Doh! I just realized that you are using my old repo... I should mark it as
deprecated!!!

This is an old, incomplete, unsupported version... You should be using:
https://github.com/InfoSec812/sonar-auth-google

Hope that helps!

Deven

**Comment by yermulnik** [comment]
Aha, I see... Indeed, you'd better mark this repo as deprecated. At least please add remark into README =) Appreciate your explanation and quick replies.
Does `InfoSec812/sonar-auth-google` support setting like `sonar.oauth2.authLocation` as you designed it for `InfoSec812/sonar-oauth2`? The thing is that I'm looking for a plugin to connect SonarQube to our own corporate auth server.

**Comment by InfoSec812** [comment]
It does indeed. And though the name indicates otherwise, it still supports
multiple oauth2 providers.

Deven

**Comment by yermulnik** [comment]
Thanx for the answer. I looked through the params of `InfoSec812/sonar-auth-google`, but it's not clear to me how can I set it up to use our auth server =( Can you please guide me? I've got `Client ID`, `Client Secrept Key` and `Auth URL`. Are those sufficient or should I ask our sec.team for some additional params?

**Comment by yermulnik** [comment]
Seems I can do that by myself  — after installing plugin it is obvious what is where =) Thanx again.

**Comment by InfoSec812** [comment]
Glad to hear it!

Deven
